version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: i-itsm-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: i-itsm
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - i-itsm

  redis:
    image: redis:7.2-alpine
    container_name: i-itsm-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - i-itsm

  mailhog:
    image: mailhog/mailhog:latest
    container_name: i-itsm-mailhog
    restart: unless-stopped
    ports:
      - '1025:1025'  # SMTP
      - '8025:8025'  # Web UI
    networks:
      - i-itsm

volumes:
  mongo_data:
  mongo_config:
  redis_data:

networks:
  i-itsm:
    driver: bridge
